# Generated by Django 5.2.1 on 2025-06-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
